# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
  terraform {
   backend "s3" {
    bucket = "devoptech-dev-terraform-backend"
    key    = "contolplane/terraform.tfstate"
    region = "ap-south-1"
  }  
}
