name: Connect to EC2 and Run Commands

on:
  workflow_dispatch:
    inputs:  
      action:
        type: choice
        description: Connect
        options:
          - connect
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH
      run: |
        sudo apt-get update
        sudo apt-get install -y openssh-client

    - name: Set up SSH key
      run: |
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H your-ec2-instance-ip >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts

    - name: Connect to EC2
      run: |
        ssh -i ~/.ssh/id_rsa ubuntu@"${{ secrets.DNS }}"

    - name: Run Commands on EC2
      run: |
        # Replace these commands with the actual commands you want to run
        echo "Hello from GitHub Actions"
        kubectl get po -A
