name: Deploy Infrastructure

on:
  push:
    branches:
      - dev

jobs:
  tf_fmt:
    name: Deploy microk8s cluster
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v1

    - name: Terraform Init
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.4.0
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: 'cluster'
        tf_actions_comment: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: 'Terraform Validate'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.4.0
        tf_actions_subcommand: 'validate'
        tf_actions_working_dir: 'cluster'
        tf_actions_comment: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: 'Terraform Plan'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.4.0
        tf_actions_subcommand: 'plan'
        tf_actions_working_dir: 'cluster'
        tf_actions_comment: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: 'Terraform Apply'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.4.0
        tf_actions_subcommand: 'apply'
        tf_actions_working_dir: 'cluster'
        tf_actions_comment: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        